- name: install epel repo
  yum: name=epel-release state=present update_cache=yes

- name: install nodejs
  yum: name=nodejs state=present

- name: install npm
  yum: name=npm state=present

- name: Create target directory
  file: path=/var/lib/local/iac-app state=directory mode=0755

- name: copy over node app
  copy: src='index.js' dest='/var/lib/local/iac-app/index.js'

- name: copy over package.json
  copy: src='package.json' dest='/var/lib/local/iac-app/package.json'

- name: install app
  npm:
    path: /var/lib/local/iac-app

#https://stackoverflow.com/questions/20919222/ansible-hangs-when-starting-node-js-server/21385202
- name: "Install forever (to run Node.js app)."
  npm: name=forever global=yes state=present

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "Start example Node.js app."
  command: forever start /var/lib/local/iac-app/index.js
  when: "forever_list.stdout.find('/path/to/app.js') == -1"